; ModuleID = 'src/global.c'
source_filename = "src/global.c"
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-unknown"

%struct.RD_DATA = type { double, [16 x [16 x i16]], [16 x [16 x i16]], [16 x [16 x i16]], ptr, ptr, i32, i16, [4 x i32], [4 x i32], ptr, [16 x i8], i32, i64, i32, ptr, ptr, [2 x [4 x [4 x i8]]], i32, i32, i32, i32, i32, i32, i32, i32, i32 }

@top_pic = dso_local local_unnamed_addr global ptr null, align 8
@bottom_pic = dso_local local_unnamed_addr global ptr null, align 8
@frame_pic = dso_local local_unnamed_addr global ptr null, align 8
@frame_pic_1 = dso_local local_unnamed_addr global ptr null, align 8
@frame_pic_2 = dso_local local_unnamed_addr global ptr null, align 8
@frame_pic_3 = dso_local local_unnamed_addr global ptr null, align 8
@imgY_org = dso_local local_unnamed_addr global ptr null, align 8
@imgUV_org = dso_local local_unnamed_addr global ptr null, align 8
@img4Y_tmp = dso_local local_unnamed_addr global ptr null, align 8
@yPicPos = dso_local local_unnamed_addr global ptr null, align 8
@xPicPos = dso_local local_unnamed_addr global ptr null, align 8
@log2_max_frame_num_minus4 = dso_local local_unnamed_addr global i32 0, align 4
@log2_max_pic_order_cnt_lsb_minus4 = dso_local local_unnamed_addr global i32 0, align 4
@me_tot_time = dso_local local_unnamed_addr global i32 0, align 4
@me_time = dso_local local_unnamed_addr global i32 0, align 4
@active_pps = dso_local local_unnamed_addr global ptr null, align 8
@active_sps = dso_local local_unnamed_addr global ptr null, align 8
@mb_adaptive = dso_local local_unnamed_addr global i32 0, align 4
@MBPairIsField = dso_local local_unnamed_addr global i32 0, align 4
@wp_weight = dso_local local_unnamed_addr global ptr null, align 8
@wp_offset = dso_local local_unnamed_addr global ptr null, align 8
@wbp_weight = dso_local local_unnamed_addr global ptr null, align 8
@luma_log_weight_denom = dso_local local_unnamed_addr global i32 0, align 4
@chroma_log_weight_denom = dso_local local_unnamed_addr global i32 0, align 4
@wp_luma_round = dso_local local_unnamed_addr global i32 0, align 4
@wp_chroma_round = dso_local local_unnamed_addr global i32 0, align 4
@imgY_org_top = dso_local local_unnamed_addr global ptr null, align 8
@imgY_org_bot = dso_local local_unnamed_addr global ptr null, align 8
@imgUV_org_top = dso_local local_unnamed_addr global ptr null, align 8
@imgUV_org_bot = dso_local local_unnamed_addr global ptr null, align 8
@imgY_org_frm = dso_local local_unnamed_addr global ptr null, align 8
@imgUV_org_frm = dso_local local_unnamed_addr global ptr null, align 8
@imgY_com = dso_local local_unnamed_addr global ptr null, align 8
@imgUV_com = dso_local local_unnamed_addr global ptr null, align 8
@direct_ref_idx = dso_local local_unnamed_addr global ptr null, align 8
@direct_pdir = dso_local local_unnamed_addr global ptr null, align 8
@pixel_map = dso_local local_unnamed_addr global ptr null, align 8
@refresh_map = dso_local local_unnamed_addr global ptr null, align 8
@intras = dso_local local_unnamed_addr global i32 0, align 4
@frame_ctr = dso_local local_unnamed_addr global [5 x i32] zeroinitializer, align 4
@frame_no = dso_local local_unnamed_addr global i32 0, align 4
@nextP_tr_fld = dso_local local_unnamed_addr global i32 0, align 4
@nextP_tr_frm = dso_local local_unnamed_addr global i32 0, align 4
@tot_time = dso_local local_unnamed_addr global i32 0, align 4
@lrec = dso_local local_unnamed_addr global ptr null, align 8
@lrec_uv = dso_local local_unnamed_addr global ptr null, align 8
@si_frame_indicator = dso_local local_unnamed_addr global i32 0, align 4
@sp2_frame_indicator = dso_local local_unnamed_addr global i32 0, align 4
@number_sp2_frames = dso_local local_unnamed_addr global i32 0, align 4
@giRDOpt_B8OnlyFlag = dso_local local_unnamed_addr global i32 0, align 4
@gaaiMBAFF_NZCoeff = dso_local local_unnamed_addr global [4 x [12 x i32]] zeroinitializer, align 4
@Bytes_After_Header = dso_local local_unnamed_addr global i32 0, align 4
@rpc_bytes_to_go = dso_local local_unnamed_addr global i32 0, align 4
@rpc_bits_to_go = dso_local local_unnamed_addr global i32 0, align 4
@p_stat = dso_local local_unnamed_addr global ptr null, align 8
@p_log = dso_local local_unnamed_addr global ptr null, align 8
@p_trace = dso_local local_unnamed_addr global ptr null, align 8
@p_in = dso_local local_unnamed_addr global i32 0, align 4
@p_dec = dso_local local_unnamed_addr global i32 0, align 4
@errortext = dso_local local_unnamed_addr global [300 x i8] zeroinitializer, align 1
@resTrans_R = dso_local local_unnamed_addr global [16 x [16 x i32]] zeroinitializer, align 4
@resTrans_G = dso_local local_unnamed_addr global [16 x [16 x i32]] zeroinitializer, align 4
@resTrans_B = dso_local local_unnamed_addr global [16 x [16 x i32]] zeroinitializer, align 4
@rec_resR = dso_local local_unnamed_addr global [16 x [16 x i32]] zeroinitializer, align 4
@rec_resG = dso_local local_unnamed_addr global [16 x [16 x i32]] zeroinitializer, align 4
@rec_resB = dso_local local_unnamed_addr global [16 x [16 x i32]] zeroinitializer, align 4
@mprRGB = dso_local local_unnamed_addr global [3 x [16 x [16 x i32]]] zeroinitializer, align 4
@dc_level = dso_local local_unnamed_addr global [2 x [4 x [4 x i32]]] zeroinitializer, align 4
@dc_level_temp = dso_local local_unnamed_addr global [2 x [4 x [4 x i32]]] zeroinitializer, align 4
@cbp_chroma_block = dso_local local_unnamed_addr global [2 x [4 x [4 x i32]]] zeroinitializer, align 4
@cbp_chroma_block_temp = dso_local local_unnamed_addr global [2 x [4 x [4 x i32]]] zeroinitializer, align 4
@b8_ipredmode8x8 = dso_local local_unnamed_addr global [4 x [4 x i8]] zeroinitializer, align 1
@b8_intra_pred_modes8x8 = dso_local local_unnamed_addr global [16 x i8] zeroinitializer, align 1
@gop_structure = dso_local local_unnamed_addr global ptr null, align 8
@rdopt = dso_local local_unnamed_addr global ptr null, align 8
@rddata_top_frame_mb = dso_local local_unnamed_addr global %struct.RD_DATA zeroinitializer, align 8
@rddata_bot_frame_mb = dso_local local_unnamed_addr global %struct.RD_DATA zeroinitializer, align 8
@rddata_top_field_mb = dso_local local_unnamed_addr global %struct.RD_DATA zeroinitializer, align 8
@rddata_bot_field_mb = dso_local local_unnamed_addr global %struct.RD_DATA zeroinitializer, align 8

!llvm.module.flags = !{!0, !1, !2, !4}
!llvm.ident = !{!5}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 1, !"target-abi", !"lp64d"}
!2 = !{i32 6, !"riscv-isa", !3}
!3 = !{!"rv64i2p1_m2p0_a2p1_f2p2_d2p2_zicsr2p0_zifencei2p0"}
!4 = !{i32 8, !"SmallDataLimit", i32 8}
!5 = !{!"clang version 19.0.0git (https://github.com/llvm/llvm-project.git 4b702946006cfa9be9ab646ce5fc5b25248edd81)"}
